site_name: AQA Computer Science Documentation
theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'green'
  logo:
    icon: 'desktop_windows'
  custom_dir: 'theme'
repo_name: 'comp500/cs-docs-mkdocs'
repo_url: 'https://github.com/comp500/cs-docs-mkdocs'
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=AM_HTMLorMML"
nav:
  - Home: "index.md"
  - 4.5 Fundamentals of data representation:
      - 4.5.1 Number systems: "4/5/number-systems.md"
      - 4.5.2 Number bases: "4/5/number-bases.md"
      - 4.5.3 Units of information: "4/5/units-of-information.md"
      - 4.5.4 Binary Number System: "4/5/binary-number-system.md"
      - 4.5.5 Information coding systems: "4/5/information-coding-systems.md"
      - 4.5.6 Representing images, sound and other data:
          - 4.5.6.1 Bit patterns: "4/5/6/bit-patterns.md"
          - 4.5.6.2 Analogue and digital: "4/5/6/analogue-and-digital.md"
          - 4.5.6.3 Analogue/digital conversion: "4/5/6/analogue-digital-conversion.md"
          - 4.5.6.4 Bitmapped graphics: "4/5/6/bitmap.md"
          - 4.5.6.5 Vector graphics: "4/5/6/vector.md"
          - 4.5.6.6 Vector graphics versus bitmapped graphics: "4/5/6/vector-vs-bitmap.md"
          - 4.5.6.7 Digital Representation of Sound: "4/5/6/digital-representation-of-sound.md"
          - 4.5.6.8 Musical Instrument Digital Interface (MIDI): "4/5/6/midi.md"
          - 4.5.6.9 Data compression: "4/5/6/compression.md"
          - 4.5.6.10 Encryption: "4/5/6/encryption.md"
  - 4.6 Fundamentals of computer systems:
      - 4.6.1 Hardware and Software:
          - 4.6.1.1 Relationship between hardware and software: "4/6/1/hardware-and-software.md"
          - 4.6.1.2 Types of software: "4/6/1/types-of-software.md"
          - 4.6.1.3 System software: "4/6/1/system-software.md"
          - 4.6.1.4 Operating systems: "4/6/1/operating-systems.md"
      - 4.6.2 Classification of programming languages: "4/6/classification-of-languages.md"
      - 4.6.3 Types of program translator: "4/6/types-of-translator.md"
      - 4.6.4 Logic gates: "4/6/logic-gates.md"
      - 4.6.5 Boolean algebra: "4/6/boolean-algebra.md"
  - 4.7 Fundamentals of computer organisation and architecture:
      - 4.7.1 Internal hardware components of a computer: "4/7/internalcomponents/index.md"
      - 4.7.2 The stored program concept: "4/7/stored-program-concept/index.md"
      - 4.7.3 Structure and role of the processor and its components: "4/7/processor.md"
      - 4.7.4 External hardware devices: "4/7/external-hardware-devices/index.md"
  - 4.8 Consequences of uses of computing:
      - 4.8.1 Individual (moral), social (ethical), legal and cultural issues and opportunities: "4/8/legislation.md"
  - About: "about.md"